### ISSUE TITLE
TOML to LV should report an error when some element are not found in the TOML data

### ISSUE THREAD

**Issue by AntoineChalons** [AntoineChalons/lv-toml#13]
example : the TOML string is
> [error]
> status = true

And the boolean label in LabVIEW has a typo "sttus"

Currently the default value of teh data type is used and no error is returned.
The VI should return an error saying "hey, I couldn't find the boolean "sttus", is it a typo?"

**Comment by justiceb** [comment]
This would be a departure from the paradigm set by JSONtext, no?:
![image](https://user-images.githubusercontent.com/7429922/114728446-b78f8b80-9d04-11eb-8899-43a5a2fc8a6e.png)

**Comment by AntoineChalons** [comment]
in order to preserve retro-compatibility, an option will be added to return an error (code 543019) if an element is not found in the TOML data.
by default this option will be disabled (optional connector on the pane with false by default)
to enable this new option, connect a "true" boolean to the optional connector to obtain the new behaviour.

**Comment by AntoineChalons** [comment]
> 
> 
> This would be a departure from the paradigm set by JSONtext, no?:
> ![image](https://user-images.githubusercontent.com/7429922/114728446-b78f8b80-9d04-11eb-8899-43a5a2fc8a6e.png)

Yes, it would, [the comment I posted just a minute ago](https://github.com/AntoineChalons/lv-toml/issues/13#issuecomment-820154602) (I hadn't seen your message) should be ok for you, right?

**Comment by AntoineChalons** [comment]
See the unit test VI I created and my comments in it

![Capture](https://user-images.githubusercontent.com/1894167/114824931-d86be580-9dc5-11eb-9cf3-2a216c2ea3a0.PNG)

**Comment by justiceb** [comment]
Best of both worlds!  Perfect
